version: '3'

services:
  pmwiki:
    build: .
    container_name: ${APP_NAME}
    # See: https://stackoverflow.com/a/38986676
    image: liecorp/php-apache:vN827
    user: "${UID}:${GID}"
    restart: unless-stopped
    volumes:
      - "./site:/var/www/html/"
      - "./server.conf:/etc/apache/sites-enabled/server.conf"
    ports:
      - "${APP_DOCK_PORT}:80"

